# Generated by Django 5.0.4 on 2025-12-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compounds',
            field=models.TextField(blank=True, help_text='Перечислите ингредиенты через запятую', null=True, verbose_name='Состав'),
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Преимущество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='catalog.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение галереи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product', verbose_name='Товар')),
            ],
        ),
    ]
