# Generated by Django 5.0.4 on 2025-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_image_remove_product_compounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Номер WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
        ),
    ]
